services:
  db:
    image: postgres:17.5
    container_name: postgres_17_5
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5435:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

  app:
    build: .
    container_name: image_app
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: ${POSTGRES_DB}
      DB_USER: ${POSTGRES_USER}
      DB_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ./images:/images
      - ./logs:/logs
      - ./static:/app/static
    expose:
      - 5000
    restart: unless-stopped
    command: >
      sh -c "mkdir -p /images /logs && chmod -R 775 /images /logs && python app.py"

  nginx:
    image: nginx:latest
    container_name: image_nginx
    ports:
      - "8000:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./images:/images
      - ./static:/app/static
      - ./logs/nginx:/var/log/nginx
    depends_on:
      - app
    restart: unless-stopped
    command: >
      sh -c "mkdir -p /images && chmod -R 775 /images && nginx -g 'daemon off;'"

volumes:
  pg_data: